# Generated by Django 4.0.8 on 2023-02-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataLoggingApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='demDailyData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('user', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('sentFrom', models.CharField(max_length=200)),
                ('sentTo', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=200)),
                ('primaryCat', models.CharField(max_length=200)),
                ('groupCat', models.CharField(max_length=200)),
            ],
        ),
    ]
